apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-gjok
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-spsu-tenant/quarkus/devfile-sample-code-with-quarkus-gjok@sha256:678a5a97096dff998d83328e933175f961cd523b193d402862300aec5599ca39
        name: my-java-quarkus
        resources: {}
status: {}
