apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-gjok
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-gjok
    app.kubernetes.io/part-of: quarkus
  name: devfile-sample-code-with-quarkus-gjok
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-gjok
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-gjok
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-spsu-tenant/quarkus/devfile-sample-code-with-quarkus-gjok@sha256:678a5a97096dff998d83328e933175f961cd523b193d402862300aec5599ca39
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
